# Generated by Django 4.2.5 on 2023-09-29 16:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDirectCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=128)),
                ('int', models.IntegerField(default=1)),
                ('bool', models.BooleanField(default=False)),
                ('choice_int', models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=1)),
                ('choice_str', models.CharField(choices=[('UK', 'United Kingdom'), ('US', 'United States')], default='UK', max_length=9)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'default_related_name': 'test',
            },
        ),
        migrations.CreateModel(
            name='TestIncludedRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_included_relation', models.CharField(default='', max_length=128)),
                ('int_included_relation', models.IntegerField(default=1)),
                ('bool_included_relation', models.BooleanField(default=False)),
                ('choice_int_included_relation', models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=1)),
                ('choice_str_included_relation', models.CharField(choices=[('UK', 'United Kingdom'), ('US', 'United States')], default='UK', max_length=9)),
                ('array_included_relation', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=2)),
            ],
            options={
                'verbose_name': 'Test Included Relation',
                'verbose_name_plural': 'Test Included Relations',
                'db_table': 'test_included_relation',
                'default_related_name': 'test_included_relation',
            },
        ),
        migrations.CreateModel(
            name='TestIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_included', models.CharField(default='', max_length=128)),
                ('int_included', models.IntegerField(default=1)),
                ('bool_included', models.BooleanField(default=False)),
                ('choice_int_included', models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=1)),
                ('choice_str_included', models.CharField(choices=[('UK', 'United Kingdom'), ('US', 'United States')], default='UK', max_length=9)),
                ('array_included', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2)),
                ('foreign_key_included', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_included_relation', to='aiodrf.testincludedrelation')),
                ('many_to_many_included', models.ManyToManyField(blank=True, related_name='test_included_relation_many', to='aiodrf.testincludedrelation')),
            ],
            options={
                'verbose_name': 'Test Included',
                'verbose_name_plural': 'Test Included',
                'db_table': 'test_included',
                'default_related_name': 'test_included',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=128)),
                ('int', models.IntegerField(default=1)),
                ('bool', models.BooleanField(default=False)),
                ('choice_int', models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=1)),
                ('choice_str', models.CharField(choices=[('UK', 'United Kingdom'), ('US', 'United States')], default='UK', max_length=9)),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2)),
                ('foreign_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_included', to='aiodrf.testincluded')),
                ('many_to_many', models.ManyToManyField(blank=True, related_name='test_included_many', to='aiodrf.testincluded')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'default_related_name': 'test',
            },
        ),
    ]
