# Generated by Django 4.2.5 on 2023-09-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiodrf', '0003_test_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdirectcon',
            name='foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_dir_test_included', to='aiodrf.testincluded'),
        ),
    ]
