# Generated by Django 4.2.5 on 2023-09-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiodrf', '0004_testdirectcon_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='array',
        ),
        migrations.RemoveField(
            model_name='testincluded',
            name='array_included',
        ),
        migrations.RemoveField(
            model_name='testincludedrelation',
            name='array_included_relation',
        ),
    ]
