# Generated by Django 4.2.5 on 2023-10-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiodrf', '0005_remove_test_array_remove_testincluded_array_included_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDirectCon',
        ),
    ]
